-- Application records are private. Only the trusted server connects to this schema.
CREATE SCHEMA academy;
REVOKE ALL ON SCHEMA academy FROM PUBLIC, anon, authenticated;
CREATE TABLE academy.visual_drafts (user_id text PRIMARY KEY, content text NOT NULL, revision integer NOT NULL DEFAULT 1, updated_at text NOT NULL);
CREATE TABLE academy.visual_site (id integer PRIMARY KEY, content text NOT NULL, revision integer NOT NULL DEFAULT 1, updated_at text NOT NULL);
CREATE TABLE academy.prototype_settings (id text PRIMARY KEY, content text NOT NULL, revision integer NOT NULL DEFAULT 1, updated_at text NOT NULL);
CREATE TABLE academy.education_enrolments (user_id text PRIMARY KEY, reference text NOT NULL UNIQUE, name text NOT NULL, path_id text NOT NULL, answers text NOT NULL DEFAULT '{}', snapshot text NOT NULL, completed text NOT NULL DEFAULT '[]', created_at text NOT NULL, updated_at text NOT NULL);
CREATE INDEX idx_enrolments_updated ON academy.education_enrolments(updated_at DESC);
CREATE TABLE academy.chat_students (id text PRIMARY KEY, user_id text NOT NULL UNIQUE, name text NOT NULL, email text NOT NULL, status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended')), code_hash text UNIQUE, code_expires bigint NOT NULL DEFAULT 0, created_at bigint NOT NULL);
CREATE INDEX idx_students_email ON academy.chat_students(lower(email));
CREATE TABLE academy.chat_sessions (hash text PRIMARY KEY, student_id text NOT NULL REFERENCES academy.chat_students(id) ON DELETE CASCADE, expires_at bigint NOT NULL);
CREATE INDEX idx_sessions_student ON academy.chat_sessions(student_id);
CREATE INDEX idx_sessions_expiry ON academy.chat_sessions(expires_at);
CREATE TABLE academy.chat_messages (seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id text NOT NULL UNIQUE, student_id text NOT NULL REFERENCES academy.chat_students(id) ON DELETE CASCADE, sender text NOT NULL CHECK(sender IN ('admin','client')), body text NOT NULL, attachment_id text, created_at bigint NOT NULL);
CREATE INDEX idx_messages_student_seq ON academy.chat_messages(student_id,seq);
CREATE TABLE academy.chat_state (student_id text NOT NULL REFERENCES academy.chat_students(id) ON DELETE CASCADE, role text NOT NULL CHECK(role IN ('admin','client')), typing_until bigint NOT NULL DEFAULT 0, read_seq bigint NOT NULL DEFAULT 0, PRIMARY KEY(student_id,role));
CREATE TABLE academy.chat_limits (key text PRIMARY KEY, count integer NOT NULL, expires bigint NOT NULL);
CREATE INDEX idx_limits_expiry ON academy.chat_limits(expires);
CREATE TABLE academy.media_files (id text PRIMARY KEY, storage_key text NOT NULL UNIQUE, student_id text REFERENCES academy.chat_students(id) ON DELETE CASCADE, user_id text NOT NULL, scope text NOT NULL CHECK(scope IN ('chat','verification','background')), role text NOT NULL CHECK(role IN ('admin','client')), name text NOT NULL, mime text NOT NULL, size bigint NOT NULL CHECK(size>0 AND size<=52428800), created_at bigint NOT NULL);
CREATE INDEX idx_media_student ON academy.media_files(student_id);
CREATE INDEX idx_media_user ON academy.media_files(user_id,scope);
-- Upload reservations authorize direct uploads and protect the per-student quota.
CREATE TABLE academy.media_uploads (id text PRIMARY KEY, actor text NOT NULL, storage_key text NOT NULL UNIQUE, student_id text REFERENCES academy.chat_students(id) ON DELETE SET NULL, user_id text NOT NULL, scope text NOT NULL, role text NOT NULL, name text NOT NULL, claimed_type text NOT NULL, size bigint NOT NULL CHECK(size>0 AND size<=52428800), expires_at bigint NOT NULL);
CREATE INDEX idx_uploads_user ON academy.media_uploads(user_id,expires_at);
CREATE INDEX idx_uploads_student ON academy.media_uploads(student_id);
-- RLS deliberately has no public policies. Application authorization is in the server APIs.
DO $$ DECLARE t record; BEGIN
 FOR t IN SELECT tablename FROM pg_tables WHERE schemaname='academy' LOOP
  EXECUTE format('ALTER TABLE academy.%I ENABLE ROW LEVEL SECURITY',t.tablename);
  EXECUTE format('REVOKE ALL ON academy.%I FROM PUBLIC, anon, authenticated',t.tablename);
 END LOOP;
END $$;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA academy FROM PUBLIC, anon, authenticated;
