// Private transactional notification outbox. No card data, access codes or attachments.
const noticeEmail=value=>typeof value==='string'&&value.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)&&!/[\r\n]/.test(value);
const noticePreview=text=>Array.from(String(text||'').replace(/https?:\/\/\S+/gi,'[link omitted]').replace(/\b[a-f0-9]{32,}\b/gi,'[private code omitted]').replace(/\b(?:\d[ -]?){13,19}\b/g,'[number omitted]').replace(/[\r\n\t]+/g,' ')).slice(0,120).join('');
const noticeTestMode=env=>env.SQUARE_ENVIRONMENT==='sandbox'&&env.SANDBOX_EMAIL_TEST_TO==='goddess@houseofvanessa.com';
const noticeEnabled=env=>env.TRANSACTIONAL_EMAIL_ENABLED==='true'&&emailReady(env)&&(env.SQUARE_ENVIRONMENT==='production'||noticeTestMode(env));
const noticeOrigin=env=>{try{const u=new URL(env.SQUARE_SITE_URL);const hosts=env.SQUARE_ENVIRONMENT==='sandbox'?['goddessvanessa-git-square-sandbox-system-admin.vercel.app']:['houseofvanessa.com','www.houseofvanessa.com'];return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&hosts.includes(u.hostname)?u.origin:null;}catch{return null;}};
async function notifyEvent(env,kind,key,data){const id='notice:'+await chatHash(kind+':'+key),now=Date.now();await db(env).prepare('INSERT INTO prototype_settings(id,content,revision,updated_at) VALUES(?,?,1,?) ON CONFLICT(id) DO NOTHING').bind(id,JSON.stringify({kind,...data,createdAt:now,state:'pending',attempts:0}),new Date(now).toISOString()).run();}
const noticeEscape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function noticeHTML(title,text,link,label){return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f7eff4;color:#2c1b25;font-family:Arial,sans-serif"><table role="presentation" style="width:100%;padding:24px 12px"><tr><td><table role="presentation" style="width:100%;max-width:540px;margin:auto;background:#fffafd;border:1px solid #dfbdce;border-radius:20px;padding:28px"><tr><td><p style="color:#9b305f;letter-spacing:2px;font-size:12px;font-weight:bold">HOUSE OF VANESSA</p><h1 style="font-size:24px;line-height:1.3">'+noticeEscape(title)+'</h1>'+text.split('\n\n').map(p=>'<p style="font-size:15px;line-height:1.65;white-space:pre-wrap;overflow-wrap:anywhere">'+noticeEscape(p)+'</p>').join('')+'<p style="margin:24px 0"><a href="'+noticeEscape(link)+'" style="display:inline-block;border-radius:24px;background:#9b305f;color:#fff;text-decoration:none;padding:13px 22px;font-weight:bold">'+noticeEscape(label)+'</a></p><p style="font-size:12px;color:#654350;line-height:1.5">A private account reminder. No attachments or access codes are included.</p></td></tr></table></td></tr></table></body></html>';}
function noticeThreshold(end,total,now){const left=end-now;return left<=0?null:left<=3600000?'1h':left<=86400000&&total>86400000?'24h':left<=7*86400000&&total>7*86400000?'7d':null;}
async function noticeQueue(env,events){if(!events.length)return;const now=Date.now(),rows=await Promise.all(events.slice(0,500).map(async e=>['notice:'+await chatHash(e.kind+':'+e.key),JSON.stringify({kind:e.kind,...e.data,createdAt:now,state:'pending',attempts:0}),new Date(now).toISOString()]));await db(env).prepare('INSERT INTO prototype_settings(id,content,revision,updated_at) VALUES '+rows.map(()=>'(?,?,1,?)').join(',')+' ON CONFLICT(id) DO NOTHING').bind(...rows.flat()).run();}
async function noticeUnread(env,now=Date.now(),enqueue=true){
 const rows=await db(env).prepare("SELECT s.id,s.name,s.email,s.user_id,m.sender,MIN(m.created_at) AS oldest,MAX(m.seq) AS latest,COALESCE(st.read_seq,0) AS read_seq FROM chat_students s JOIN chat_messages m ON m.student_id=s.id LEFT JOIN chat_state st ON st.student_id=s.id AND st.role=CASE WHEN m.sender='client' THEN 'admin' ELSE 'client' END WHERE s.status='active' AND m.seq>COALESCE(st.read_seq,0) AND m.created_at<=? "+(enqueue?"AND NOT EXISTS (SELECT 1 FROM prototype_settings n WHERE n.id LIKE 'notice:%' AND n.content::jsonb->>'kind'='unread' AND n.content::jsonb->>'studentId'=s.id AND n.content::jsonb->>'recipient'=CASE WHEN m.sender='client' THEN 'admin' ELSE 'client' END AND n.content::jsonb->>'readSeq'=COALESCE(st.read_seq,0)::text) ":"")+"GROUP BY s.id,s.name,s.email,s.user_id,m.sender,st.read_seq ORDER BY MIN(m.created_at) LIMIT 100").bind(now-300000).all();
 if(enqueue)await noticeQueue(env,rows.results.map(row=>({kind:'unread',key:row.id+':'+row.sender+':'+row.read_seq,data:{studentId:row.id,recipient:row.sender==='client'?'admin':'client',readSeq:row.read_seq,seq:row.latest}})));
 return rows.results;
}
async function noticeExpiry(env,now=Date.now()){
 const rows=await db(env).prepare("SELECT s.id,p.content::jsonb->>'expiresAt' AS expires_at,p.content::jsonb->>'paidAt' AS paid_at FROM chat_students s JOIN prototype_settings p ON p.content::jsonb->>'user'=s.user_id AND p.content::jsonb->>'stage'='contract' WHERE s.status='active' AND p.id LIKE ? AND p.content::jsonb->>'status'='paid' AND p.content::jsonb->>'expiresAt'>? AND p.content::jsonb->>'expiresAt'<=? ORDER BY p.content::jsonb->>'expiresAt' LIMIT 500").bind('sq-'+squareMode(env)+'-c-%',new Date(now).toISOString(),new Date(now+7*86400000).toISOString()).all();
 const events=[];for(const row of rows.results){const end=Date.parse(row.expires_at),total=end-Date.parse(row.paid_at),threshold=noticeThreshold(end,total,now);if(threshold)events.push({kind:'expiry',key:row.id+':'+row.expires_at+':'+threshold,data:{studentId:row.id,expiresAt:row.expires_at,threshold}});}await noticeQueue(env,events);
}
async function noticePayload(env,n){
 const origin=noticeOrigin(env);if(!origin)return null;
 let student=n.studentId?await db(env).prepare('SELECT id,user_id,name,email,status FROM chat_students WHERE id=?').bind(n.studentId).first():null;
 if(n.studentId&&(!student||student.status!=='active'))return null;
 let to=n.email||student?.email,subject='House of Vanessa · Account update',body='';
 if(n.kind==='unread'){
  const sender=n.recipient==='admin'?'client':'admin',state=await db(env).prepare('SELECT read_seq FROM chat_state WHERE student_id=? AND role=?').bind(student.id,n.recipient).first();if((state?.read_seq||0)>=n.seq)return null;
  const m=await db(env).prepare('SELECT body,attachment_id,created_at FROM chat_messages WHERE student_id=? AND sender=? AND seq>? AND seq<=? ORDER BY seq DESC LIMIT 1').bind(student.id,sender,state?.read_seq||0,n.seq).first();if(!m)return null;
  to=n.recipient==='admin'?env.ADMIN_NOTIFICATION_EMAIL:student.email;
  const preview=m.attachment_id?'Shared attachment':noticePreview(m.body);
  subject='House of Vanessa · Unread message';body='You have an unread message'+(n.recipient==='admin'?' from '+student.name:' from Goddess Vanessa')+'.\n\n'+preview+'\n\nOpen your conversation: '+origin+(n.recipient==='admin'?'/dashboard.html':'/chat.html');
 }else if(n.kind==='expiry'){
  const {contract}=await squarePaymentState(env,student.user_id);if(contract?.status!=='paid'||contract.expiresAt!==n.expiresAt||Date.parse(n.expiresAt)<=Date.now())return null;
  if(noticeThreshold(Date.parse(n.expiresAt),Date.parse(n.expiresAt)-Date.parse(contract.paidAt),Date.now())!==n.threshold)return null;
  subject='House of Vanessa · Your contract is ending soon';body='Your contract ends '+new Intl.DateTimeFormat('en-GB',{dateStyle:'full',timeStyle:'short',timeZone:'UTC'}).format(new Date(n.expiresAt))+' UTC.\n\nChoose a plan to renew or extend your access. There is no automatic charge.\n\n'+origin+'/plans.html';
 }else{const labels={payment:'Payment confirmed',application:'Application received',access:'Chat access ready',renewal:'Contract extended'};subject='House of Vanessa · '+(labels[n.kind]||'Account update');body=(labels[n.kind]||'Account update')+'.'+(n.plan?'\n\nPlan: '+n.plan:'')+(n.expiresAt?'\nAccess ends: '+n.expiresAt:'')+'\n\n'+origin+(n.kind==='access'?'/access.html':n.kind==='renewal'?'/plans.html':'/application.html');}
 if(!noticeEmail(to))return null;
 const link=origin+(n.kind==='unread'?(n.recipient==='admin'?'/dashboard.html':'/chat.html'):n.kind==='expiry'?'/plans.html':'/access.html'),title=n.kind==='unread'?'A message is waiting for you':n.kind==='expiry'?'Your contract is ending soon':'Your account update';
 const test=env.SQUARE_ENVIRONMENT==='sandbox',prefix=test?'Sandbox test — '+(n.recipient==='admin'?'Goddess':'Sub')+' reminder.\n\n':'';if(test&&!noticeTestMode(env))return null;
 return {from:env.EMAIL_FROM,to:[test?env.SANDBOX_EMAIL_TEST_TO:to],subject:(test?'[Sandbox] ':'')+subject,text:prefix+body+'\n\nThis is a transactional account notification. Your private access code is never included.',html:noticeHTML(title,prefix+body,link,n.kind==='expiry'?'View contract plans':'Open your account')};
}
async function noticeDispatch(env){
 if(!noticeEnabled(env)||!noticeOrigin(env))return {enabled:false,sent:0};const stopAt=Date.now()+18000;
 const abandoned=await db(env).prepare("SELECT id,content,revision FROM prototype_settings WHERE id LIKE 'notice:%' AND content::jsonb->>'state'='sending' AND updated_at<? LIMIT 20").bind(new Date(Date.now()-120000).toISOString()).all();for(const row of abandoned.results){const n=JSON.parse(row.content);await db(env).prepare('UPDATE prototype_settings SET content=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify({...n,...(Date.now()-(n.firstAttemptAt||n.createdAt)>=20*3600000?{payload:undefined}:{}),state:Date.now()-(n.firstAttemptAt||n.createdAt)<20*3600000?'pending':'review'}),row.id,row.revision).run();}
 await noticeUnread(env);await noticeExpiry(env);
 const rows=await db(env).prepare("SELECT id,content,revision FROM prototype_settings WHERE id LIKE 'notice:%' AND content::jsonb->>'state'='pending' ORDER BY updated_at LIMIT 20").all();let sent=0;
 for(const row of rows.results){if(Date.now()>stopAt-500)break;const n=JSON.parse(row.content);if(n.nextAttempt&&n.nextAttempt>Date.now())continue;if(n.payload&&Date.now()-(n.firstAttemptAt||n.createdAt)>=20*3600000){await db(env).prepare('UPDATE prototype_settings SET content=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify({...n,payload:undefined,state:'review'}),row.id,row.revision).run();continue;}const payload=await noticePayload(env,n);if(!payload){await db(env).prepare('UPDATE prototype_settings SET content=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify({...n,payload:undefined,state:'skipped'}),row.id,row.revision).run();continue;}
  if(n.payload&&(JSON.stringify(n.payload.to)!==JSON.stringify(payload.to)||n.payload.from!==payload.from)){await db(env).prepare('UPDATE prototype_settings SET content=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify({...n,payload:undefined,state:'review'}),row.id,row.revision).run();continue;}
  const claimed={...n,state:'sending',payload:n.payload||payload,startedAt:Date.now(),firstAttemptAt:n.firstAttemptAt||Date.now(),attempts:n.attempts+1};const locked=await db(env).prepare('UPDATE prototype_settings SET content=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?').bind(JSON.stringify(claimed),new Date().toISOString(),row.id,row.revision).run();if(!locked.meta.changes)continue;const rechecked=await noticePayload(env,n);if(!rechecked||JSON.stringify(rechecked.to)!==JSON.stringify(claimed.payload.to)||rechecked.from!==claimed.payload.from){const {payload:removed,...safe}=claimed;await db(env).prepare('UPDATE prototype_settings SET content=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify({...safe,state:'skipped'}),row.id,row.revision+1).run();continue;}
  // Resend idempotency is valid for 24h; uncertain sends are never retried outside it.
  let state='review',providerId=null;try{const response=await (env.EMAIL_FETCH||fetch)('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+env.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':row.id},body:JSON.stringify(claimed.payload),signal:AbortSignal.timeout(Math.max(1,Math.min(8000,stopAt-Date.now())))});const result=response.ok?await response.json():null;if(result&&typeof result.id==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(result.id)){state='accepted';providerId=result.id;sent++;}else if(response.status===429||response.status>=500)state='pending';}catch{state='pending';}
  if(claimed.attempts>=5||Date.now()-claimed.firstAttemptAt>20*3600000&&state==='pending')state='review';
  const {payload:discard,...safe}=claimed;await db(env).prepare('UPDATE prototype_settings SET content=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?').bind(JSON.stringify({...safe,...(state==='pending'?{payload:claimed.payload}:{}),state,...(providerId?{providerId}:{}),nextAttempt:Date.now()+60000}),new Date().toISOString(),row.id,row.revision+1).run();
 }
 return {enabled:true,sent};
}
async function notificationAPI(request,env,url){
 if(url.pathname==='/api/cron/notifications'){
  if(request.method!=='GET')return json({error:'Method not allowed'},405);
  if(typeof env.CRON_SECRET!=='string'||env.CRON_SECRET.length<32||request.headers.get('authorization')!=='Bearer '+env.CRON_SECRET)return json({error:'Unauthorized'},401);
  const started=Date.now(),result=await noticeDispatch(env);await db(env).prepare('INSERT INTO prototype_settings(id,content,revision,updated_at) VALUES(?,?,1,?) ON CONFLICT(id) DO UPDATE SET content=excluded.content,revision=prototype_settings.revision+1,updated_at=excluded.updated_at').bind('notification-run:'+squareMode(env),JSON.stringify({at:Date.now(),enabled:result.enabled,sent:result.sent,duration:Date.now()-started}),new Date().toISOString()).run();return json(result);
 }
 const owner=!!request.headers.get('oai-authenticated-user-id')&&request.headers.get('oai-authenticated-user-email')?.toLowerCase()===EDUCATION_OWNER&&request.headers.get('x-chat-role')!=='student';if(!owner)return json({error:'Goddess access required'},403);if(request.method!=='GET')return json({error:'Method not allowed'},405);
 if(url.pathname==='/api/chat/email-previews'){const samples=noticeSamples(env);if(samples.sandbox){const rows=await db(env).prepare("SELECT content::jsonb->>'state' AS state,COUNT(*)::int AS count FROM prototype_settings WHERE id LIKE 'notice:%' GROUP BY content::jsonb->>'state'").all(),run=await db(env).prepare('SELECT content FROM prototype_settings WHERE id=?').bind('notification-run:'+squareMode(env)).first();samples.queue=Object.fromEntries(rows.results.filter(r=>['pending','sending','accepted','skipped','review'].includes(r.state)).map(r=>[r.state,r.count]));samples.lastRun=run?JSON.parse(run.content).at:null;}return json(samples);}
 const unread=await noticeUnread(env,Date.now(),false);const rows=await db(env).prepare("SELECT id,content FROM prototype_settings WHERE id LIKE 'notice:%' ORDER BY updated_at DESC LIMIT 60").all();
 return json({emailReady:noticeEnabled(env),events:rows.results.map(r=>{const n=JSON.parse(r.content);return {id:r.id,kind:n.kind,studentId:n.studentId||null,at:n.createdAt,state:n.state,plan:n.plan||null,expiresAt:n.expiresAt||null};}),unread:unread.filter(r=>r.sender==='client').map(r=>({studentId:r.id,name:r.name,at:r.oldest})),schedulerReady:typeof env.CRON_SECRET==='string'&&env.CRON_SECRET.length>=32});
}

function noticeSamples(env){const sandbox=env.SQUARE_ENVIRONMENT==='sandbox',origin=noticeOrigin(env);if(!sandbox||!origin)return {error:'Email previews are available on the Sandbox site only.'};const content=[{id:'sub-unread',title:'Sub · Unread message',text:'You have an unread message from Goddess Vanessa.\n\nHow has your week been?\n\nOpen your conversation: '+origin+'/chat.html',path:'/chat.html',label:'Open conversation'},{id:'goddess-unread',title:'Goddess · Unread message',text:'You have an unread message from a sample Sub.\n\nI have a question about my next task.\n\nOpen your conversation: '+origin+'/dashboard.html',path:'/dashboard.html',label:'Open Dashboard'},{id:'expiry',title:'Sub · Contract ending soon',text:'Your contract ends soon.\n\nChoose a plan to renew or extend your access. There is no automatic charge.',path:'/plans.html',label:'View contract plans'}];return {sandbox:true,configured:emailReady(env),deliveryEnabled:noticeEnabled(env),testRecipientReady:noticeTestMode(env),schedulerReady:typeof env.CRON_SECRET==='string'&&env.CRON_SECRET.length>=32,reminders:['Unread for at least 5 minutes','7 days, 24 hours and 1 hour before expiry, where applicable'],samples:content.map(c=>({id:c.id,title:c.title,html:noticeHTML(c.title,c.text,origin+c.path,c.label)}))};}
