export const release={version:'2026.10.05.6',date:'2026-10-05',title:'Sub contract purchases and transactional notifications'};
export const changelog=[
 {...release,changes:['Added a private transactional notification queue and five-minute unread reminders with short previews.','Added account events and overdue unread conversations to the admin notification centre.','Prepared full-price contract purchases with billing-only expired-account access and atomic duration extension.','Email and production plan checkout await verified sender configuration and activation.']},
 {version:'2026.10.05.5',date:'2026-10-05',title:'Square native checkout return recovery',changes:['Recovered hosted Square payments after failed attempts and recognized native tender identifiers.','Checked pending checkout on application reload and advanced confirmed entry payments without requesting another payment.','Preserved private applicant contact and server-controlled payment verification.']},
 {version:'2026.10.05.4',date:'2026-10-05',title:'Chat input visibility and keyboard layout',changes:['Kept chat input visible while long message histories scroll independently.','Bounded desktop and tablet conversation layouts and adapted mobile chat to the visible keyboard viewport.','Retained the existing theme and icon controls.']},
 {version:'2026.10.05.3',date:'2026-10-05',title:'Conversation workspace and compact overview',changes:['Made Conversations the dashboard landing tab on desktop and mobile.','Prioritized Latest Applications with compact activity/counts and collapsible trends.','Unified composer tools above the input, restored send-button contrast and proportionate icons.','Added a clear cancel-reply X that preserves the typed draft; back navigation is arrow-only.','Expanded desktop/mobile thread space and avoided marking hidden mobile conversations as read.']},
 {version:'2026.10.05.2',date:'2026-10-05',title:'Compact chat and mobile conversations',changes:['Reduced text and voice bubbles with a shared timestamp and circular reply row.','Added a mobile chat list and full-height conversation with a Chats back button.','Moved browser alerts and the client chat link to Settings, and Message all to Conversations.','Added saved pins at the top of desktop and mobile chat lists.','Removed repeated visual media labels and duplicate action icons; grouped media request icons in pink.']},
 {version:'2026.10.05.1',date:'2026-10-05',title:'Conversation experience and contract-bound access',changes:['Kept access codes valid through their contract with safe session rotation and replacement checks.','Added private replies, broadcasts, labels, galleries and voice-note draft previews.','Corrected signed video uploads, generic media labels, mobile code issuance and saved availability.','Added compact conversation and verification controls, visual activity and admin day/night contrast.','Added existing-member contract options and requests; self-service renewal payment remains pending.']},
 {version:'2026.10.04.2',date:'2026-10-04',title:'Member support and private-browser compatibility',changes:['Made optional draft storage and timeout capabilities safe in private browsers.','Added cookie preflight before consuming access codes.','Improved private video verification selection, MOV support and upload-and-send flow.','Fixed mobile contract price cards and compact admin header controls.','Added required paid-entry contact details, private Sub profiles/notes, shared galleries, emoji tools, paid-phase notifications and bounded activity counts.']},
 {version:'2026.10.04.1',date:'2026-10-04',title:'Bank verification and safe checkout recovery',changes:['Allowed bank-app switches during authentication with bounded visible-page and total deadlines.','Prevented the entry modal from obstructing Square authentication.','Added same-tab Square-hosted recovery before any recorded charge; uncertain payments keep their original confirmation identity.','Added curated bank-verification reports and a read-only Square connection check to private health tools.']},
 {version:'2026.10.03.2',date:'2026-10-03',title:'Mobile chat and upload quota fix',changes:['Fixed chat header and account menu sizing on mobile.','Kept messages visible while composing and restored chat after file selection.','Fixed numeric upload quota calculations.']},
 {version:'2026.10.03.1',date:'2026-10-03',title:'Discount and checkout recovery',changes:['Restored SUB50 repricing for untouched entry checkouts.','Scoped bank authentication CSP to checkout and preserved safe retries.']},
 {version:'2026.09.30.1',date:'2026-09-30',title:'Session and request security hardening',changes:['Locked application and sub cookies to their exact hostname with secure HttpOnly sessions.','Added streaming request limits for sign-in, application, chat and payment webhooks.','Added HTTPS, form submission and browser permission protections.']},
 {version:'2026.09.27.1',date:'2026-09-27',title:'Guided application styling',changes:['Restyled application screens with focused signup cards, choice chips and compact progress steps.','Added a mobile Continue bar while retaining the existing application stages and validation.']},
 {version:'2026.09.26.6',date:'2026-09-26',title:'Live dashboard overview & transitions',changes:['Added circular dashboard loading transitions in the site colours.','Added live totals, recent applications and a seven-day activity chart.','Updated the dashboard guide for the new layout and live workflows.']},
 {version:'2026.09.26.5',date:'2026-09-26',title:'Account menu interaction fix',changes:['Fixed premature menu dismissal when moving focus to an Account option.','Allowed link and button actions to finish before closing the dropdown.']},
 {version:'2026.09.26.4',date:'2026-09-26',title:'Compact dashboard header',changes:['Simplified the dashboard header to a notification bell and Account dropdown.','Grouped dashboard tools, availability, settings and logout into Account.','Kept mobile controls compact and keyboard accessible.']},
 {version:'2026.09.26.3',date:'2026-09-26',title:'Private Goddess code login',changes:['Added a dedicated Goddess access-code login page.','Added dashboard Settings to change the code by confirming the current code.','Added session expiry, logout, attempt limits and session revocation after code changes.']},
 {version:'2026.09.26.2',date:'2026-09-26',title:'Goddess navigation & mobile access',changes:['Made Status & Debug prominent in the dashboard header.','Added labelled navigation icons and a wrapping mobile menu.','Updated sign-in, access and error messages to refer to Goddess.']},
 {version:'2026.09.26.1',date:'2026-09-26',title:'Status centre & site identity',changes:['Added a branded favicon and home-screen icon.','Added a Goddess-only status centre with connection checks, recent server issues and a downloadable diagnostic report.','Added this dated release history.']},
 {version:'95fd2be',date:'2026-09-26',title:'Goddess-issued sub access',changes:['Subs can apply and request verification without email sign-in.','Only Vanessa can issue or replace chat access codes.','Removed sub self-service code emails; Goddess sign-in stays separate.']},
 {version:'9290a58',date:'2026-09-26',title:'Contracts & application settings',changes:['Contract names, GBP rates, questions and options share the same settings with the backend.','Added a publish review and validation for prices and options.','Saved agreements keep their original details; changed applications require a fresh review.']},
 {version:'b8d3354',date:'2026-09-26',title:'Vercel & Supabase migration',changes:['Moved hosting to Vercel with GitHub deployments.','Connected the private database and file storage.','Preserved the application, dashboard, access-code chat and visual editors.']}
];
