import fs from 'node:fs';
import path from 'node:path';
const assets={};
function walk(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,item.name);if(item.isDirectory())walk(p);else{const key='/'+path.relative('public',p).replaceAll('\\','/');const ext=path.extname(p);const type={'.svg':'image/svg+xml','.ico':'image/x-icon','.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.otf':'font/otf','.woff2':'font/woff2','.mp4':'video/mp4','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp','.txt':'text/plain; charset=utf-8'}[ext]||'application/octet-stream';assets[key]={data:fs.readFileSync(p).toString('base64'),type};}}}
const allowed=new Set(['goddess-navigation.css','goddess-navigation.js','favicon.svg','favicon.ico','apple-touch-icon.png','status.html','status.css','status.js','signin.html','signin.js','chat-media.js','preview-access.js','entry-lightbox.js','verification-inbox.js','chat-loading.js','education-review.js','student-account.js','chat.html','restored.css','restored-chat.js','client-chat.js','restored-tour.js','prototype.css','dashboard.css','course-builder.html','style.css','landing.css','landing.js','icons.js','visual.js','visual-schema.js','builder.js','builder.css','page-loading.js','index.html','application.html','access.html','dashboard.html','studio.html','education-config.js','education-shared.js','education-home.js','education-app.js','education-access.js','education-dashboard.js','education-builder.js','education.css','typography.css']);
walk('public');for(const key of Object.keys(assets)){if(!allowed.has(key.slice(1))&&!key.startsWith('/fonts/')&&!['/images/editorial-portrait.jpg','/images/hero-poster.jpg','/images/hero-loop.mp4'].includes(key))delete assets[key];}
fs.mkdirSync('dist/server',{recursive:true});fs.mkdirSync('dist/.openai',{recursive:true});
fs.writeFileSync('dist/server/index.js','const ASSETS='+JSON.stringify(assets)+';\n'+fs.readFileSync('public/education-config.js','utf8')+'\n'+fs.readFileSync('server/verification.js','utf8')+'\n'+fs.readFileSync('server/media.js','utf8')+'\n'+fs.readFileSync('server/direct-media.js','utf8')+'\n'+fs.readFileSync('server/mail.js','utf8')+'\n'+fs.readFileSync('server/chat.js','utf8')+'\n'+fs.readFileSync('server/education.js','utf8')+'\n'+fs.readFileSync('public/visual-schema.js','utf8')+'\n'+fs.readFileSync('server/visual.js','utf8')+'\n'+fs.readFileSync('server/worker.js','utf8'));
fs.rmSync('dist/public',{recursive:true,force:true});fs.mkdirSync('dist/public',{recursive:true});for(const [key,asset] of Object.entries(assets)){const dest=path.join('dist/public',key);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,Buffer.from(asset.data,'base64'));}
console.log('Built Worker with '+Object.keys(assets).length+' assets for Vercel and PostgreSQL.');
