import fs from 'node:fs';
import path from 'node:path';
const assets={};
function walk(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,item.name);if(item.isDirectory())walk(p);else{const key='/'+path.relative('public',p).replaceAll('\\','/');const ext=path.extname(p);const type={'.svg':'image/svg+xml','.ico':'image/x-icon','.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.otf':'font/otf','.woff2':'font/woff2','.mp4':'video/mp4','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp','.txt':'text/plain; charset=utf-8','.xml':'application/xml; charset=utf-8'}[ext]||'application/octet-stream';assets[key]={data:fs.readFileSync(p).toString('base64'),type};}}}
const allowed=new Set(['application-faq.js','support-payment.html','support-payment.js','images/brand/admin-feed-compose.png','sub-profile.js','sub-profile.css','application-funnel.js','application-funnel.css','application-tracking.js','square-ui.js','square-ui.css','feed-donations.js','sub-theme.css','liquid-glass.css','sub-session-route.js','feed.html','feed.js','feed.css','sub-navigation.js','admin-feed.js','admin-icons.js','admin-appearance.css','chat-refinements.js','chat-refinements.css','site-presence.js','admin-support.js','admin-support.css','robots.txt','sitemap.xml','admin-chat-notifications.js','chat-notifications-sw.js','privacy.html','privacy.css','square-payments.js','application-signup.css','dashboard-live.css','dashboard-live.js','goddess-account.css','goddess-account.js','goddess-login.css','goddess-settings.js','goddess-navigation.css','goddess-navigation.js','favicon.svg','favicon.ico','apple-touch-icon.png','status.html','status.css','status.js','signin.html','signin.js','chat-media.js','preview-access.js','entry-lightbox.js','verification-inbox.js','chat-loading.js','education-review.js','student-account.js','chat.html','restored.css','restored-chat.js','client-chat.js','restored-tour.js','prototype.css','dashboard.css','course-builder.html','style.css','landing.css','landing.js','icons.js','visual.js','visual-schema.js','builder.js','builder.css','page-loading.js','index.html','application.html','access.html','dashboard.html','studio.html','education-config.js','education-shared.js','education-home.js','education-app.js','education-access.js','education-dashboard.js','education-builder.js','education.css','typography.css']);
walk('public');for(const key of Object.keys(assets)){if(!allowed.has(key.slice(1))&&!key.startsWith('/fonts/')&&!/^\/images\/brand\/(?:vanessa-(mark|wordmark)\.png|chat-emojis\.svg|vanessa-chat-avatar\.jpg)$/.test(key)&&!/^\/images\/home\/slide-[1-4]-(desktop|mobile)\.(mp4|jpg)$/.test(key)&&!['/images/editorial-portrait.jpg','/images/hero-poster.jpg','/images/hero-loop.mp4'].includes(key))delete assets[key];}
// Preview and sandbox pages must never compete with the public domain in search.
if(process.env.VERCEL_ENV==='preview'||process.env.VERCEL_GIT_COMMIT_REF==='square-sandbox'){
 for(const [key,asset] of Object.entries(assets))if(key.endsWith('.html')){
  const html=Buffer.from(asset.data,'base64').toString('utf8').replace(/<meta name="robots"[^>]*>/g,'').replace('</head>','<meta name="robots" content="noindex, nofollow"></head>');
  asset.data=Buffer.from(html).toString('base64');
 }
 assets['/robots.txt'].data=Buffer.from('User-agent: *\nAllow: /\nDisallow: /api/\n').toString('base64');
 assets['/sitemap.xml'].data=Buffer.from('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>').toString('base64');
}
fs.mkdirSync('dist/server',{recursive:true});fs.mkdirSync('dist/.openai',{recursive:true});
fs.writeFileSync('dist/server/index.js','const ASSETS='+JSON.stringify(assets)+';\n'+fs.readFileSync('server/platform/request-body.js','utf8').replace('export async function','async function')+'\n'+fs.readFileSync('public/education-config.js','utf8')+'\n'+fs.readFileSync('server/verification.js','utf8')+'\n'+fs.readFileSync('server/media.js','utf8')+'\n'+fs.readFileSync('server/direct-media.js','utf8')+'\n'+fs.readFileSync('server/mail.js','utf8')+'\n'+fs.readFileSync('server/feed.js','utf8')+'\n'+fs.readFileSync('server/chat.js','utf8')+'\n'+fs.readFileSync('server/square.js','utf8')+'\n'+fs.readFileSync('server/application-funnel.js','utf8')+'\n'+fs.readFileSync('server/education.js','utf8')+'\n'+fs.readFileSync('public/visual-schema.js','utf8')+'\n'+fs.readFileSync('server/visual.js','utf8')+'\n'+fs.readFileSync('server/dashboard-experience.js','utf8')+'\n'+fs.readFileSync('server/worker.js','utf8'));
fs.rmSync('dist/public',{recursive:true,force:true});fs.mkdirSync('dist/public',{recursive:true});for(const [key,asset] of Object.entries(assets)){const dest=path.join('dist/public',key);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,Buffer.from(asset.data,'base64'));}
console.log('Built Worker with '+Object.keys(assets).length+' assets for Vercel and PostgreSQL.');
