import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {database} from '../server/platform/database.js';
import {hashCode} from '../server/platform/goddess-auth.js';
import {base32,totp,totpStep,sealSecret,openSecret} from '../server/platform/mfa.js';
import {handle} from '../api/index.js';
const secret=base32(Buffer.from('12345678901234567890'));
for(const [seconds,expected] of [[59,'94287082'],[1111111109,'07081804'],[1111111111,'14050471'],[1234567890,'89005924'],[2000000000,'69279037'],[20000000000,'65353130']])assert.equal(totp(secret,Math.floor(seconds/30),8),expected);
assert.equal(totpStep(secret,totp(secret,2),2,60000),null);
const envelope=await sealSecret(secret,'987654321098');assert.equal(await openSecret(envelope,'987654321098'),secret);await assert.rejects(openSecret(envelope,'wrong'));
await assert.rejects(openSecret({...envelope,tag:'00'.repeat(16)},'987654321098'));
const sql=new PGlite();await sql.exec('CREATE ROLE anon;CREATE ROLE authenticated;');await sql.exec(fs.readFileSync('supabase/schema.sql','utf8'));const DB=database(sql),code='938275461902';
await DB.prepare('INSERT INTO prototype_settings (id,content,revision,updated_at) VALUES (?,?,1,?)').bind('goddess-credential',JSON.stringify({...await hashCode(code),userId:'test-owner',initial:false}),new Date().toISOString()).run();
async function call(path,body,cookie){const r=await handle(new Request('https://academy.test/api/auth/'+path,{method:body?'POST':'GET',headers:{origin:'https://academy.test','Content-Type':'application/json',...(cookie?{cookie}:{})},body:body?JSON.stringify(body):undefined}),{DB},{DB});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
const reset=()=>DB.prepare('DELETE FROM chat_limits').run();
assert.equal((await call('mfa-start',{code})).status,401);
const login=await call('code',{code}),other=await call('code',{code});assert.equal(login.status,200);
const start=await call('mfa-start',{code},login.cookie);assert.equal(start.status,200);assert.match(start.body.secret,/^[A-Z2-7]{32}$/);
assert.equal((await call('mfa-enable',{code,factor:'invalid'},login.cookie)).status,401);
const enabled=await call('mfa-enable',{code,factor:totp(start.body.secret,Math.floor(Date.now()/30000))},login.cookie);assert.equal(enabled.status,200);assert.equal(enabled.body.recoveryCodes.length,8);
assert.equal((await call('session',null,other.cookie)).status,401);
await reset();assert.equal((await call('code',{code})).body.mfaRequired,true);
assert.equal((await call('code',{code,factor:totp(start.body.secret,Math.floor(Date.now()/30000))})).status,401);
const factor=enabled.body.recoveryCodes[0];const concurrent=await Promise.all([call('code',{code,factor}),call('code',{code,factor})]);assert.equal(concurrent.filter(r=>r.status===200).length,1);const verified=concurrent.find(r=>r.status===200);
await reset();assert.equal((await call('code',{code,factor})).status,401);assert.deepEqual((await call('mfa',null,verified.cookie)).body,{enabled:true,recoveryRemaining:7});
const changeFactor=enabled.body.recoveryCodes[1],newCode='827394615028';
assert.equal((await call('code-change',{oldCode:code,newCode:'938271',confirmCode:'938271',factor:changeFactor},verified.cookie)).status,400);
assert.equal((await call('code-change',{oldCode:code,newCode,confirmCode:newCode,factor:changeFactor},verified.cookie)).status,200);
assert.equal((await call('session',null,verified.cookie)).status,401);
await reset();const changed=await call('code',{code:newCode,factor:enabled.body.recoveryCodes[2]});assert.equal(changed.status,200);
const stored=JSON.parse((await DB.prepare('SELECT content FROM prototype_settings WHERE id=?').bind('goddess-credential').first()).content);assert.equal(await openSecret(stored.mfa.envelope,newCode),start.body.secret);assert.ok(!JSON.stringify(stored).includes(start.body.secret));assert.equal(stored.mfa.recoveryHashes.length,5);
await sql.close();console.log('MFA passed: RFC vectors, encrypted setup, wrong-key/tamper rejection, protected enrollment, OTP replay rejection, recovery concurrency, rotation and session revocation.');
